export * from "./syncFunction";
export * from "./argument";
export * from "./lastArgument";
export * from "./asyncFunction";
export * from "./overloads";
export * from "./isMatchingOverload";
export * from "./getMatchedOverload";
export * from "./allowCall";
export * from "./changeReturns";
